/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pmodul6;
import java.awt.Image; 
import javax.swing.*; 
import java.io.*; 
import javax.swing.filechooser.FileFilter; 
/**
 *
 * @author ASUS
 */
public class fGambar extends javax.swing.JFrame {
 DefaultListModel gambar;     
// buat konstanta untuk filter file    
 final String[] 
 EXT= {".jpg", ".jpeg",".gif",".tiff",".png"};
    /**
     * Creates new form fGambar
     */
    public fGambar() {
        initComponents();
         gambar = new DefaultListModel();         
         lstDaftar.setModel(gambar); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGambar = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDaftar = new javax.swing.JList<>();
        chkFit = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblGambar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGambar.setText("Pilih Gambar");
        btnGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGambarActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus Pilihan");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        lstDaftar.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstDaftar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lstDaftarAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        lstDaftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstDaftarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstDaftar);

        chkFit.setText("Fit Lebar Frame Gambar");

        jScrollPane2.setViewportView(lblGambar);
        lblGambar.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGambar)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkFit)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGambar)
                    .addComponent(btnHapus)
                    .addComponent(chkFit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGambarActionPerformed
        // TODO add your handling code here:
         JFileChooser fc = new JFileChooser();       
//Atur Filter Menggunakan Class jenisFile       
//aturan mengikuti konstanta EXT       
fc.addChoosableFileFilter(new jenisFile(EXT));       
int hasil = fc.showOpenDialog(this);       
if (hasil == JFileChooser.APPROVE_OPTION) {            
//Pilih Yes           
File file = fc.getSelectedFile();          
// Ambil nama file beserta pathnya           
String nf = file.getAbsolutePath();           
// masukkan ke listData Model gambar           
gambar.addElement(nf);
    }//GEN-LAST:event_btnGambarActionPerformed
    }
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
         int index = lstDaftar.getSelectedIndex();         
//yang di-remove adalah listData model-nya         
         gambar.remove(index);         
         lblGambar.setIcon(null);
    }//GEN-LAST:event_btnHapusActionPerformed

    private void lstDaftarAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lstDaftarAncestorAdded
        // TODO add your handling code here:
         
    }//GEN-LAST:event_lstDaftarAncestorAdded

    private void lstDaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstDaftarMouseClicked
        // TODO add your handling code here:
        //Ambil nama file gambarnya    
         String nf = lstDaftar.getSelectedValue().toString();    
// Jadikan Icon    
ImageIcon gbr = new ImageIcon(nf);
  // Jika CheckBox Fit ke Frame gambar di Check    
  if (chkFit.isSelected())       
// buat gambar mempunyai lebar 200,        
// dengan tinggi menyesuaikan       
// menggunakan algoritma default       
      gbr = new ImageIcon(gbr.getImage().getScaledInstance(200,                                  
              -1, Image.SCALE_DEFAULT));       
//tampilkan gambar         
lblGambar.setIcon(gbr);
    }//GEN-LAST:event_lstDaftarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fGambar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGambar;
    private javax.swing.JButton btnHapus;
    private javax.swing.JCheckBox chkFit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblGambar;
    private javax.swing.JList<String> lstDaftar;
    // End of variables declaration//GEN-END:variables
}
